#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Convert gesture PNGs to LVGL v8 C image descriptors.

Output format: LV_IMG_CF_TRUE_COLOR_ALPHA (16-bit color + 8-bit alpha = 3 bytes/px).
Matches lv_conf.h: LV_COLOR_DEPTH=16, LV_COLOR_16_SWAP=1 (bytes swapped in memory).

Per pixel layout in data: [color_hi, color_lo, alpha]
  where RGB565 c = (r>>3)<<11 | (g>>2)<<5 | (b>>3),
  color_hi = (c>>8)&0xFF, color_lo = c&0xFF (swap order).

Usage: python convert_gestures.py
Reads ./*.png (via 数字手势/) and writes gesture_images.c + gesture_images.h
"""
import os
from PIL import Image

# (filename, C var name, display name) in the order requested by the user
GESTURES = [
    ("1.png",   "img_gesture_1",   "1"),
    ("2.png",   "img_gesture_2",   "2"),
    ("3.png",   "img_gesture_3",   "3"),
    ("4.png",   "img_gesture_4",   "4"),
    ("5.png",   "img_gesture_5",   "5"),
    ("6.png",   "img_gesture_6",   "6"),
    ("7.png",   "img_gesture_7",   "7"),
    ("8.png",   "img_gesture_8",   "8"),
    ("10.png",  "img_gesture_10",  "10"),
    ("ok.png",  "img_gesture_ok",  "ok"),
    ("good.png","img_gesture_good","good"),
    ("love.png","img_gesture_love","love"),
]

IMG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "数字手势")
OUT_C   = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gesture_images.c")
OUT_H   = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gesture_images.h")

OUT_W = 36   # cell inner height is ~36px; keep square
OUT_H_PX = 36


def convert_pixel(rgba):
    """rgba: (r,g,b,a) 0..255 -> returns 3 bytes [hi, lo, alpha] (swapped RGB565 + alpha)."""
    r, g, b, a = rgba
    c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    hi = (c >> 8) & 0xFF
    lo = c & 0xFF
    return (hi, lo, a)


def process_image(path):
    """Return (width, height, bytes-list) for LVGL TRUE_COLOR_ALPHA, swapped."""
    im = Image.open(path).convert("RGBA")
    im = im.resize((OUT_W, OUT_H_PX), Image.LANCZOS)
    w, h = im.size
    px = im.load()
    data = []
    for y in range(h):
        for x in range(w):
            hi, lo, a = convert_pixel(px[x, y])
            data.append(hi)
            data.append(lo)
            data.append(a)
    return w, h, data


def fmt_data(data, indent="    "):
    """Format byte list as hex, 12 per line."""
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append(indent + ", ".join("0x%02X" % b for b in chunk) + ",")
    return "\n".join(lines)


def main():
    entries = []
    for fname, var, name in GESTURES:
        path = os.path.join(IMG_DIR, fname)
        if not os.path.exists(path):
            raise FileNotFoundError(path)
        w, h, data = process_image(path)
        entries.append((var, name, w, h, data))
        print("Converted %-8s -> %dx%d, %d bytes" % (fname, w, h, len(data)))

    # ---- gesture_images.c ----
    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by convert_gestures.py. Do not edit. */\n")
        f.write("/* LVGL v8 image descriptors: LV_IMG_CF_TRUE_COLOR_ALPHA, RGB565 swapped. */\n")
        f.write("#include \"gesture_images.h\"\n\n")
        for var, name, w, h, data in entries:
            f.write("/* gesture: %s (%dx%d) */\n" % (name, w, h))
            f.write("static const uint8_t %s_data[%d] = {\n" % (var, len(data)))
            f.write(fmt_data(data))
            f.write("\n};\n\n")
            f.write("const lv_img_dsc_t %s = {\n" % var)
            f.write("    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
            f.write("    .header.always_zero = 0,\n")
            f.write("    .header.reserved = 0,\n")
            f.write("    .header.w = %d,\n" % w)
            f.write("    .header.h = %d,\n" % h)
            f.write("    .data_size = %d,\n" % len(data))
            f.write("    .data = %s_data,\n" % var)
            f.write("};\n\n")

    # ---- gesture_images.h ----
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by convert_gestures.py. Do not edit. */\n")
        f.write("#ifndef GESTURE_IMAGES_H\n")
        f.write("#define GESTURE_IMAGES_H\n\n")
        f.write("#include \"lvgl.h\"\n\n")
        f.write("#ifdef __cplusplus\n")
        f.write("extern \"C\" {\n")
        f.write("#endif\n\n")
        for var, name, w, h, data in entries:
            f.write("/* gesture: %s (%dx%d) */\n" % (name, w, h))
            f.write("LV_IMG_DECLARE(%s);\n" % var)
        f.write("\n#ifdef __cplusplus\n")
        f.write("}\n")
        f.write("#endif\n\n")
        f.write("#endif /* GESTURE_IMAGES_H */\n")

    print("\nWrote: %s" % OUT_C)
    print("Wrote: %s" % OUT_H)


if __name__ == "__main__":
    main()
