[platformio]
default_envs = esp32-s3-devkitm-1

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio

build_flags =
    -O0
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    lvgl@^8.3.11

build_src_filter =
    +<ble_lvgl_arduino.ino>
    +<ble_manager.cpp>
    +<pwm_manager.cpp>
    +<ui_main.c>
    +<lcd_bsp.c>
    +<esp_lcd_sh8601.c>
    +<FT3168.c>
    +<gesture_images.c>
    -<.git>
    -<docs>
    -<test>