/* Auto-generated by convert_gestures.py. Do not edit. */
#ifndef GESTURE_IMAGES_H
#define GESTURE_IMAGES_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* gesture: 1 (36x36) */
LV_IMG_DECLARE(img_gesture_1);
/* gesture: 2 (36x36) */
LV_IMG_DECLARE(img_gesture_2);
/* gesture: 3 (36x36) */
LV_IMG_DECLARE(img_gesture_3);
/* gesture: 4 (36x36) */
LV_IMG_DECLARE(img_gesture_4);
/* gesture: 5 (36x36) */
LV_IMG_DECLARE(img_gesture_5);
/* gesture: 6 (36x36) */
LV_IMG_DECLARE(img_gesture_6);
/* gesture: 7 (36x36) */
LV_IMG_DECLARE(img_gesture_7);
/* gesture: 8 (36x36) */
LV_IMG_DECLARE(img_gesture_8);
/* gesture: 10 (36x36) */
LV_IMG_DECLARE(img_gesture_10);
/* gesture: ok (36x36) */
LV_IMG_DECLARE(img_gesture_ok);
/* gesture: good (36x36) */
LV_IMG_DECLARE(img_gesture_good);
/* gesture: love (36x36) */
LV_IMG_DECLARE(img_gesture_love);
/* gesture: stop (36x36) */
LV_IMG_DECLARE(img_gesture_stop);

#ifdef __cplusplus
}
#endif

#endif /* GESTURE_IMAGES_H */
