#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 1
#define LV_COLOR_SCREEN_TRANSP 0
#define LV_COLOR_MIX_ROUND_OFS 0

#define LV_MEM_CUSTOM 1
#if LV_MEM_CUSTOM == 0
#define LV_MEM_SIZE (48U * 1024U)
#define LV_MEM_ADR 0
#endif
#define LV_MEM_CUSTOM_INCLUDE <stdlib.h>

#define LV_MEM_BUF_MAX_NUM 16

#define LV_DISP_DEF_REFR_PERIOD 30
#define LV_INDEV_DEF_READ_PERIOD 30
#define LV_TICK_CUSTOM 0
#define LV_DPI_DEF 130

#define LV_DRAW_COMPLEX 1
#if LV_DRAW_COMPLEX != 0
#define LV_SHADOW_CACHE_SIZE 0
#define LV_CIRCLE_CACHE_SIZE 4
#endif

#define LV_LAYER_SIMPLE_BUF_SIZE          (24 * 1024)
#define LV_LAYER_SIMPLE_FALLBACK_BUF_SIZE (3 * 1024)

#define LV_IMG_CACHE_DEF_SIZE 1
#define LV_GRADIENT_MAX_STOPS 2
#define LV_MAX_TRANSFORM 0

#define LV_FONT_MONTSERRAT  1
#define LV_FONT_MONTSERRAT_8  1
#define LV_FONT_MONTSERRAT_10 1
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_22 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_DEFAULT &lv_font_montserrat_14

#define LV_USE_TEXT_UTF8 1
#define LV_USE_TEXT_ASCII 1

#define LV_USE_FS_STDIO 0
#define LV_USE_FS_POSIX 0
#define LV_USE_FS_WIN32 0
#define LV_USE_FS_SEGGER_RTT 0
#define LV_USE_FS_OS 0
#define LV_USE_FS_MEMFS 0

#define LV_USE_PNG 0
#define LV_USE_JPG 0
#define LV_USE_BMP 0
#define LV_USE_SJPG 0
#define LV_USE_GIF 0
#define LV_USE_QRCODE 0
#define LV_USE_TINY_TTF 0

#define LV_USE_SNAPSHOT 0
#define LV_USE_ANIM 1
#define LV_USE_SYSMON 0
#define LV_USE_THEME_DEFAULT 1
#define LV_THEME_DEFAULT_DARK 1

#define LV_USE_WIDGETS 1
#define LV_USE_OBJ 1
#define LV_USE_OBJ_POS 1
#define LV_USE_OBJ_SIZE 1
#define LV_USE_OBJ_STYLE 1
#define LV_USE_OBJ_TREE 1
#define LV_USE_OBJ_EVENT 1
#define LV_USE_ARC 1
#define LV_USE_BAR 1
#define LV_USE_BTN 1
#define LV_USE_BTNMATRIX 1
#define LV_USE_CHECKBOX 1
#define LV_USE_DROPDOWN 1
#define LV_USE_IMG 1
#define LV_USE_LABEL 1
#define LV_USE_LINE 1
#define LV_USE_ROLLER 1
#define LV_USE_SLIDER 1
#define LV_USE_SWITCH 1
#define LV_USE_TABLE 1
#define LV_USE_TEXTAREA 1
#define LV_USE_WIN 1

#define LV_USE_MSGBOX 1
#define LV_USE_SPINBOX 1
#define LV_USE_SCALE 1
#define LV_USE_LIST 1
#define LV_USE_MENU 1
#define LV_USE_TABVIEW 1
#define LV_USE_TILEVIEW 1
#define LV_USE_CHART 0
#define LV_USE_GAGE 0
#define LV_USE_KEYBOARD 0
#define LV_USE_LED 0
#define LV_USE_METER 0
#define LV_USE_SPINNER 0

#define LV_USE_USER_DATA 1

#define LV_USE_PERF_MONITOR 0
#define LV_USE_MEM_MONITOR 0
#define LV_USE_SYSMON 0

#define LV_USE_DBG_ASSERT 1

#endif
